### PR TITLE
Ballot fix : Issue 672 - Changes to Immunisation site ValueSet binding Postiion

### LINKED ISSUE #672: AUBaseImmunisation - the binding of 'site' has been provided at site.coding level not at CodeableConcept level
The binding of 'site' has been added at 'site.coding' level not at CodeableConcept level. As a result, if inherited from AUBaseImmunisation, then the binding is still showing as 'CodesForImmunizationSiteOfAdministration' with 'example' strength.  

Screen Shot 2021-12-08 at 8 47 06 am

### PR DESCRIPTION
**Pull request by shovanroy-github**
Partial fix for FHIRIG-161 

Fixes #672 & similar Fix for 'route'

### CODE REVIEW

**Comment by dtr-agency** [comment]
@oridashi  and @shovanroy-github, the Immunization resource has several ballot issues raised: FHIRIG-182, FHIRIG-181, FHIRIG-158. Initial triage discussion notes that Immunization.site should be a preferred binding and no slicing. That approach addresses this issue but with a different solution.

We are looking to handle changes with reference to ballot issues via an approved Ballot fix PR.

**Review by dtr-agency — CHANGES_REQUESTED** [review]
@oridashi  and @shovanroy-github, the Immunization resource has several ballot issues raised: FHIRIG-182, FHIRIG-181, FHIRIG-158 that have gone through an initial triage. The desired approach to dealing with the slicing on this element has been discussed:

> Immunization.site should be a preferred binding and no slicing. 

That approach addresses this issue with a different solution - the design intention is not to impose a required binding, the original technique was to slice on coding which still allowed for a free text alternative but the binding approach in AU Base has moved on to apply preferred bindings at the element level.

This PR should be declined with reference to decision taken on ballot comment.

**Comment by shovanroy-github** [comment]
@dtr-agency(cc: @oridashi) Thanks for the feedback. I was also unsure why there was a required binding. 
Anyway, the issue that raised was not related to the binding strength, rather it was the position where the ValueSet was bounded.

I'll make the changes in the PR

Shovan

**Review by dtr-agency — COMMENTED** [review]
There is one additional change that will need to be submitted. As the location of the binding has changed the following entry in ignoreWarnings.txt will need to be changed:

> The valueSet reference https://healthterminologies.gov.au/fhir/ValueSet/immunisation-anatomical-site-1 on element Immunization.site.coding could not be resolved

**Review by dtr-agency — APPROVED** [review]
The file changes are good. Please edit the **origin comment of the PR** to state 'partial fix for FHIRIG-161' and also link directly to the raised GitHub e.g. 'fixes #672'.

**Pull request merged**
